basket/urls.py
from django.urls import path

from basket.views import BasketDetailView, BasketManagementAjaxView

urlpatterns = [
    path("manage/", BasketManagementAjaxView.as_view(), name="basket_management_ajax"),
    path('', BasketDetailView.as_view(), name="basket"),
]

marketplace/urls.py
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.urls import path, include
from django.views.static import serve

from comment.views import BasicCommandCreateView
# from core.views import HomePageView
from listing.views import IndexView
from product.views import ProductDetailsView
from user.views import login_ajax_view, register_ajax_view, logout_user_view


urlpatterns = i18n_patterns(
    path('admin/', admin.site.urls),
    path('product/<slug:slug>/comments/add/', BasicCommandCreateView.as_view(), name="add_comment"),
    path('product/<slug:slug>/', ProductDetailsView.as_view(), name="product_details"),
    path('basket/', include('basket.urls')),
    path('shipment/', include('shipment.urls')),
    path('listing/', include('listing.urls')),
    path('payment/', include('payment.urls', namespace='payment')),
    path('register', register_ajax_view, name="register"),
    path('login/', login_ajax_view, name="login"),
    path('logout/', logout_user_view, name="logout"),
    path('', IndexView.as_view(), name="homepage"),
)

if settings.DEBUG:
    if 'debug_toolbar' in settings.INSTALLED_APPS:
        import debug_toolbar
        urlpatterns += [
            path('__debug__/', include(debug_toolbar.urls)),
        ]
    urlpatterns += [path('media/<path:path>', serve, {'document_root': settings.MEDIA_ROOT})]

comment/models.py
from django.db import models
from django.utils.translation import ugettext_lazy as _

from product.models import Product
from user.models import User


class Comment(models.Model):
    author = models.ForeignKey(User, verbose_name=_("Author"), related_name="comments", on_delete=models.CASCADE)
    product = models.ForeignKey(Product, verbose_name=_("Product"), related_name="comments", on_delete=models.CASCADE)
    rate = models.IntegerField(_("Rate"), default=100)
    subject = models.CharField(_("Subject"), max_length=200, blank=True, null=True)
    message = models.TextField(_("Comment"), blank=True, null=True)
    verified = models.BooleanField(_("Verified"), default=False)
    created_at = models.DateTimeField(_("Created"), auto_now_add=True, editable=False)
    modified_at = models.DateTimeField(_("Modified"), auto_now=True, editable=False)

    class Meta:
        verbose_name = _("Comment")
        verbose_name_plural = _("Comments")
        ordering = ("-modified_at",)

    def __str__(self):
        name = self.author.__str__()
        return f"{name} - {self.rate}"

product/models.py
import sys
from io import BytesIO
from typing import Union

from PIL import Image, ExifTags
from django.core.files.uploadedfile import InMemoryUploadedFile
from django.db import models
from django.db.models import Avg
from django.utils.timezone import now
from django.utils.translation import ugettext_lazy as _

from tags.models import Tag


def get_product_image_path(instance, filename):
    extension = filename.split(".")[-1]
    file_name = instance.slug
    year = now().year
    return f"products/{year}/{file_name}.{extension}"


class StatusChoices(models.IntegerChoices):
    DRAFT = 1, _("Draft")
    PUBLIC = 2, _("Public")
    HIDDEN = 3, _("Hidden")


class ProductCategory(models.Model):
    """Categories for products."""
    name = models.CharField(_("Name"), max_length=100)
    slug = models.SlugField(_("Slug"), max_length=50, unique=True)
    description = models.TextField(_("Description"), blank=True)
    template_icon = models.CharField(_("Template icon"), max_length=50, blank=True, null=True)
    rank = models.IntegerField(_("Order rank"), default=1)
    created_at = models.DateTimeField(_("Created"), auto_now_add=True, editable=False)
    modified_at = models.DateTimeField(_("Modified"), auto_now=True, editable=False)

    class Meta:
        verbose_name = _("Product category")
        verbose_name_plural = _("Product categories")
        ordering = ("rank",)

    def __str__(self) -> str:
        return self.name


class Product(models.Model):
    """Product definition."""
    name = models.CharField(_("Name"), max_length=255, blank=False, null=False)
    slug = models.SlugField(_("Slug"), max_length=50, unique=True)
    category = models.ForeignKey(
        ProductCategory, verbose_name=_("Category"), related_name="products", on_delete=models.CASCADE,
        blank=False, null=False
    )
    description = models.TextField(_("Description"), blank=True)
    price = models.FloatField(_("Price"), default=0.0)
    available_quantity = models.IntegerField(_("Available quantity"), default=0, null=True, blank=True)
    barcode = models.CharField(_("Barcode"), max_length=20, null=True, blank=True)
    tags = models.ManyToManyField(Tag, verbose_name=_("Tags"), related_name="products", blank=True)
    status = models.IntegerField(_("Status"), choices=StatusChoices.choices, default=StatusChoices.DRAFT)
    created_at = models.DateTimeField(_("Created"), auto_now_add=True, editable=False)
    modified_at = models.DateTimeField(_("Modified"), auto_now=True, editable=False)

    @property
    def main_image(self):
        return self.images.order_by("rank", "modified_at").first()

    @property
    def average_rating(self) -> Union[int, None]:
        try:
            return int(self.comments.all().aggregate(avg_rating=Avg("rate"))["avg_rating"])
        except TypeError:
            return None

    class Meta:
        verbose_name = _("Product")
        verbose_name_plural = _("Products")
        ordering = ("modified_at",)

    def __str__(self) -> str:
        return self.name


class ProductImages(models.Model):
    """Image library for the product."""
    title = models.CharField(_("Title"), max_length=255, blank=False, null=False)
    slug = models.SlugField(_("Slug"), max_length=50, unique=True)
    product = models.ForeignKey(
        Product, verbose_name=_("Product"), related_name="images", on_delete=models.CASCADE,
        blank=False, null=False
    )
    image = models.ImageField(_("Image"), upload_to=get_product_image_path)
    rank = models.IntegerField(_("Rank"), default=2)
    created_at = models.DateTimeField(_("Created"), auto_now_add=True, editable=False)
    modified_at = models.DateTimeField(_("Modified"), auto_now=True, editable=False)

    class Meta:
        verbose_name = _("Product image")
        verbose_name_plural = _("Product images")
        ordering = ("rank", "modified_at")

    def __str__(self) -> str:
        return "{title} for {product}".format(title=self.title, product=self.product.name)

    def save(self, *args, **kwargs):
        im = Image.open(self.image)
        output = BytesIO()
        min_size = 256
        orientation = 0
        # find rotation exif tag
        for orientation in ExifTags.TAGS.keys():
            if ExifTags.TAGS[orientation] == 'Orientation':
                break
        try:
            exif = dict(im._getexif().items())
            if exif[orientation] == 3:
                im = im.rotate(180, expand=True)
            elif exif[orientation] == 6:
                im = im.rotate(270, expand=True)
            elif exif[orientation] == 8:
                im = im.rotate(90, expand=True)
        except (AttributeError, KeyError, IndexError):
            pass
        im = im.convert("RGB")
        x, y = im.size
        size = max(min_size, x, y)
        new_im = Image.new('RGB', (size, size), (255, 255, 255))
        new_im.paste(im, (int((size - x) / 2), int((size - y) / 2)))
        new_im.save(output, format='JPEG', quality=100)
        output.seek(0)
        self.image = InMemoryUploadedFile(
            output, 'ImageField', "%s.jpg" % self.image.name.split('.')[0],
            'image/jpeg', sys.getsizeof(output), None
        )
        im.close()
        new_im.close()
        super().save(*args, **kwargs)


class PropertyOption(models.Model):
    name = models.CharField(_("Property name"), max_length=100, unique=True)

    class Meta:
        verbose_name = _("Property option")
        verbose_name_plural = _("Property options")
        ordering = ("name",)

    def __str__(self):
        return self.name


class ProductProperty(models.Model):
    product = models.ForeignKey(
        Product, verbose_name=_("Product"), related_name="properties", on_delete=models.CASCADE
    )
    option = models.ForeignKey(
        PropertyOption, verbose_name=_("Option"), related_name="usages", on_delete=models.CASCADE
    )
    value = models.CharField(_("Value"), max_length=255)
    is_main_property = models.BooleanField(_("Main property"), default=False)

    class Meta:
        verbose_name = _("Product property")
        verbose_name_plural = _("Product properties")
        ordering = ("product", "option")
        unique_together = ["product", "option"]

product/views.py
from django.http import Http404
from django.utils.translation import ugettext_lazy as _
from django.views.generic import TemplateView

from comment.forms import CommentForm
from product.models import Product, StatusChoices


class ProductDetailsView(TemplateView):
    template_name = "product/details.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        slug = kwargs.get("slug")
        product = Product.objects.filter(
            slug=slug, status=StatusChoices.PUBLIC
        ).select_related("category").prefetch_related("images", "tags").first()
        if not product:
            raise Http404(_(f"Product {slug} was not found!"))
        context["product"] = product
        context["product_category"] = product.category
        context["main_properties"] = product.properties.filter(is_main_property=True).select_related("option")
        context["additional_properties"] = product.properties.all().select_related("option")
        context["comments"] = product.comments.filter(verified=True, message__isnull=False).exclude(message="")
        context["comment_form"] = CommentForm()
        context["similar_products"] = Product.objects.filter(
            category=product.category
        ).exclude(pk=product.pk).prefetch_related("properties")[:4]
        return context

product/templates/product/details.html
{% extends "base.html" %}
{% load i18n static humanize thumbnail %}
{% block title %}{{ product.name }}{% endblock %}
{% block content %}
    <div class="container" style="padding-top:5%">
        <div class="row justify-content-center">
            <div class="col-lg-3 col-md-3 col-sm-12">
                <div id="productImages" class="carousel slide" data-ride="carousel" data-interval="false">
                    <ol class="carousel-indicators">
                        {% for image in product.images.all %}
                            <li data-target="#productImages" data-slide-to="{{ forloop.counter0 }}"
                                    {% if forloop.first %} class="active"{% endif %}></li>
                        {% endfor %}
                    </ol>
                    <div class="carousel-inner">
                        {% for image in product.images.all %}
                            <div class="carousel-item{% if forloop.first %} active{% endif %}">
                                {% thumbnail image.image "350x350" crop="center" as im %}
                                    <a href="{{ image.image.url }}" data-lightbox="roadtrip"
                                       data-title="{{ image.title }}">
                                        <img src="{{ im.url }}" class="d-block w-100 carousel-image"
                                             alt="{{ image.title }}">
                                    </a>
                                {% endthumbnail %}
                            </div>
                        {% endfor %}
                    </div>
                    <a class="carousel-control-prev" href="#productImages" role="button" data-slide="prev">
                        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                        <span class="sr-only">{% trans "Previous" %}</span>
                    </a>
                    <a class="carousel-control-next" href="#productImages" role="button" data-slide="next">
                        <span class="carousel-control-next-icon" aria-hidden="true"></span>
                        <span class="sr-only">{% trans "Next" %}</span>
                    </a>
                </div>
            </div>
            <div class="col-lg-1 col-md-1 col-sm-0"></div>
            <div class="col-lg-5 col-md-5 col-sm-10">
                <div class="h3 my-auto">{{ product.name }}</div>
                <div>
                    <p class="mb-1 font-weight-bold">{{ product.price|floatformat:2 }} <i class="fas fa-lira-sign"></i>
                    </p>
                    <p class="mb-1">Rating: {% if product.average_rating %}{{ product.average_rating }}/100{% else %}
                        {% trans "N/A" %}{% endif %}</p>
                    {% for property in main_properties %}
                        <p class="{% if forloop.last %}mb-5{% else %}mb-1{% endif %}">{{ property.option.name }}: {{ property.value }}</p>
                    {% endfor %}
                    <button type="button" class="btn btn-danger add-basket-item" data-product-slug="{{ product.slug }}"
                            data-quantity="1">
                        <i class="fas fa-shopping-basket"></i> {% trans "Add to basket" %}
                    </button>
                </div>
            </div>
        </div>
        <div class="clean-block"></div>
        <div>
            <div class="h3 my-auto">{% trans "Additional details" %}</div>
            <hr/>
            <table class="table table-bordered">
                <tbody>
                {% for property in additional_properties %}
                    <tr>
                        <th scope="row">{{ property.option.name }}</th>
                        <td>{% if property.value == "check" %}
                            <i class="fa fa-check-circle green-text"></i>{% elif property.value == "no-check" %}
                            <i class="fa fa-times-circle red-text"></i>{% else %}{{ property.value }}{% endif %}</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
        <div class="clean-block"></div>
        {% if similar_products %}
            <div class="h3 my-auto">{% trans "Similar products" %}</div>
            <hr/>
            <div class="card-group">
                {% for similar_product in similar_products %}
                    <div class="card">
                        <a href="{% url "product_details" slug=similar_product.slug %}" class="similar_product_item">
                            {% thumbnail similar_product.main_image.image "350x350" crop="center" as im %}
                            <img src="{{ im.url }}" class="card-img-top" alt="{{ similar_product.main_image.title }}">
                            {% endthumbnail %}
                        </a>
                        <div class="card-body">
                            <h5 class="card-title">{{ similar_product.name }}</h5>
                            <p class="card-text">
                            <span class="mb-1 font-weight-bold">{{ product.price|floatformat:2 }} <i class="fas fa-lira-sign"></i></span>
                            <ul>
                                {% for property in similar_product.properties.all %}
                                    {% if property.is_main_property %}
                                        <li>
                                            {{ property.option.name }}:
                                            {% if property.value == "check" %}
                                                <i class="fa fa-check-circle green-text"></i>
                                            {% elif property.value == "no-check" %}
                                                <i class="fa fa-times-circle red-text"></i>
                                            {% else %}
                                                {{ property.value }}
                                            {% endif %}
                                        </li>
                                    {% endif %}
                                {% endfor %}
                            </ul>
                            </p>
                        </div>
                        <div class="card-footer">
                            <small class="text-muted"></small>
                        </div>
                    </div>
                {% endfor %}
            </div>
            <div class="clean-block"></div>
        {% endif %}
        <nav>
            <div class="nav nav-tabs" id="nav-tab" role="tablist">
                <a class="nav-item nav-link active text-dark" id="nav-home-tab" data-toggle="tab" href="#nav-home"
                   role="tab" aria-controls="nav-home" aria-selected="true">{% trans "Comments" %}</a>
                {% if not user.is_registered %}
                    <a class="nav-link" href="#" data-toggle="modal"
                       data-target="#signinModal">{% trans "Add Comment" %}</a>
                {% else %}
                    <a class="nav-item nav-link text-dark" id="nav-profile-tab" data-toggle="tab" href="#nav-addComment"
                       role="tab" aria-controls="nav-profile" aria-selected="false">{% trans "Add Comment" %}</a>
                {% endif %}
            </div>
        </nav>
        <div class="tab-content" id="nav-tabContent">
            <div class="tab-pane fade show active" id="nav-home" role="tabpanel" aria-labelledby="nav-home-tab">
                {% if comments %}
                    {% for comment in comments %}
                        <div class="media p-3">
                            <div class="media-body">
                                <div class="well well-lg bg-light rounded p-3"
                                     style="box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2)">
                                    <div class="d-flex justify-content-between">
                                        <div>
                                            <span class="fa fa-star{% if comment.rate >= 0 %} checked{% endif %}"></span>
                                            <span class="fa fa-star{% if comment.rate > 20 %} checked{% endif %}"></span>
                                            <span class="fa fa-star{% if comment.rate > 40 %} checked{% endif %}"></span>
                                            <span class="fa fa-star{% if comment.rate > 60 %} checked{% endif %}"></span>
                                            <span class="fa fa-star{% if comment.rate > 80 %} checked{% endif %}"></span>
                                        </div>
                                        <p><small>{{ comment.modified_at|naturaltime }}</small></p>
                                    </div>
                                    <h6 class="media-heading text-uppercase reviews">{{ comment.subject }}</h6>
                                    <p class="media-comment">{{ comment.message }}</p>
                                    <div class="d-flex justify-content-between">
                                        <div>
                                        </div>
                                        <p><small>{% if comment.author.is_registered %}{{ comment.author }}{% else %}
                                            {% trans "Anonymous" %}{% endif %}</small></p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                {% else %}
                    <div class="media p-3">
                        <div class="media-body">
                            <div class="well well-lg bg-light rounded p-3"
                                 style="box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2)">
                                <p>{% trans "No comments added yet." %}</p>
                            </div>
                        </div>
                    </div>
                {% endif %}
            </div>
            <!-- Add Comment -->
            <div class="tab-pane fade" id="nav-addComment" role="tabpanel" aria-labelledby="nav-profile-tab">
                <form action="{% url "add_comment" slug=product.slug %}" method="post">
                    {% csrf_token %}
                    <div class="p-3">
                        <div class="form-group">
                            <label for="comment_rating" class="lfloat mr-2">{% trans "Rating:" %}</label>
                            <div class="d-flex justify-content-start" id="rating">
                                <div><span class="fa fa-star" id="1"></span></div>
                                <div><span class="fa fa-star" id="2"></span></div>
                                <div><span class="fa fa-star" id="3"></span></div>
                                <div><span class="fa fa-star" id="4"></span></div>
                                <div><span class="fa fa-star" id="5"></span></div>
                            </div>
                            <input type="hidden" name="rate" value="0" required id="id_rate">
                        </div>
                        <div class="form-group">
                            <label for="comment_subject">{% trans "Heading" %}</label>
                            <input type="text" class="form-control" id="comment_subject" name="subject" maxlength="200">
                        </div>
                        <div class="form-group form-group-lg">
                            <label for="comment_description">{% trans "Comment" %}</label>
                            <textarea class="form-control" id="comment_description" rows="5" name="message"></textarea>
                        </div>
                        <button type="submit" class="btn btn-success">{% trans "Add" %}</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}
{% block extraJS %}
    <script>
        let rating = document.getElementById("rating");
        let score;
        rating.addEventListener("mouseover", function (event) {
            let score1 = event.target.id;
            let i;
            for (i = 1; i <= parseInt(score1); i++) {
                document.getElementById(i).style.color = "orange";
            }
            for (i = parseInt(score1) + 1; i <= 5; i++) {
                document.getElementById(i).style.color = "";
            }
        }, false)
        rating.addEventListener("mouseout", function (event) {
            for (i = 1 || 1; i <= window.score; i++) {
                document.getElementById(i).style.color = "orange";
            }
            for (i = window.score + 1 || 1; i <= 5; i++) {
                document.getElementById(i).style.color = "";
            }
        }, false)
        rating.addEventListener("click", function (event) {
            let score2 = event.target.id;
            window.score = parseInt(score2);
            let i;
            for (i = 1; i <= parseInt(score2); i++) {
                document.getElementById(i).style.color = "orange";
            }
            for (i = score2 + 1; i <= 5; i++) {
                document.getElementById(i).style.color = "";
            }
            $("#id_rate").val(parseInt(score2) * 20);
        }, false)

    </script>
{% endblock %}