basket/urls.py
from django.urls import path

from basket.views import BasketDetailView, BasketManagementAjaxView

urlpatterns = [
    path("manage/", BasketManagementAjaxView.as_view(), name="basket_management_ajax"),
    path('', BasketDetailView.as_view(), name="basket"),
]

marketplace/urls.py
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.urls import path, include
from django.views.static import serve

from comment.views import BasicCommandCreateView
# from core.views import HomePageView
from listing.views import IndexView
from product.views import ProductDetailsView
from user.views import login_ajax_view, register_ajax_view, logout_user_view


urlpatterns = i18n_patterns(
    path('admin/', admin.site.urls),
    path('product/<slug:slug>/comments/add/', BasicCommandCreateView.as_view(), name="add_comment"),
    path('product/<slug:slug>/', ProductDetailsView.as_view(), name="product_details"),
    path('basket/', include('basket.urls')),
    path('shipment/', include('shipment.urls')),
    path('listing/', include('listing.urls')),
    path('payment/', include('payment.urls', namespace='payment')),
    path('register', register_ajax_view, name="register"),
    path('login/', login_ajax_view, name="login"),
    path('logout/', logout_user_view, name="logout"),
    path('', IndexView.as_view(), name="homepage"),
)

if settings.DEBUG:
    if 'debug_toolbar' in settings.INSTALLED_APPS:
        import debug_toolbar
        urlpatterns += [
            path('__debug__/', include(debug_toolbar.urls)),
        ]
    urlpatterns += [path('media/<path:path>', serve, {'document_root': settings.MEDIA_ROOT})]

payment/urls.py
from django.urls import path
from payment.views import PaymentView, mail_view

app_name = 'payment'

urlpatterns = [
    path('',PaymentView.as_view(), name="cart"),
    path('confirm/',mail_view, name="confirm_payment")
]

payment/models.py
from django.db import models

# Create your models here.

payment/views.py
from django.shortcuts import render
from django.template import loader
from django.views.generic import TemplateView, View
from basket.models import Basket, BasketItem
from shipment.models import Shipment
from django.shortcuts import render
from marketplace.settings import EMAIL_HOST_USER
from django.core.mail import send_mail
from django.template.loader import render_to_string
from django.utils.html import strip_tags
from shipment.models import Shipment

# Create your views here.


class PaymentView(TemplateView):
    template_name = "payment/detail.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['user'] = self.request.user
        basket = Basket.current_basket(user=self.request.user)

        basket_items = BasketItem.objects.filter(
            basket=basket,
        )
        context['basket_items'] = basket_items

        subtotal = sum(basket_item.product.price for basket_item in basket_items)
        context['subtotal'] = subtotal

        total = 0
        if basket:
            total = basket.coupon_code.get_discounted_value(subtotal) if basket.coupon_code else subtotal
        context['total'] = total

        context['discount'] = total - subtotal
        shipments = Shipment.objects.filter(user=self.request.user)
        for shipment in shipments:
            if shipment.selection == 2 or shipment.selection == 3:
                context['name'] = shipment.name
                context['surname'] = shipment.surname
                context['email'] = shipment.email
                context['neighborhood'] = shipment.neighborhood
                context['others'] = shipment.others
                context['district'] = shipment.district
                context['city'] = shipment.get_city_display()

        return context


def mail_view(request):
    if request.method == 'POST':
        recipient = request.POST.get('email')
        domain = request.get_host()
        print(domain)
        basket = Basket.current_basket(user=request.user)

        basket_items = BasketItem.objects.filter(
            basket=basket,
        )
        subtotal = sum(basket_item.product.price for basket_item in basket_items)
        total = 0
        if basket:
            total = basket.coupon_code.get_discounted_value(subtotal) if basket.coupon_code else subtotal
        discount = total - subtotal
        subject = 'Your order has been received'
        shipment = Shipment.objects.filter(user=request.user).values()
        for element in shipment:
            Address_name = element['name']
            Address_surname = element['surname']
            Address_email = element['email']
            Address_neighborhood = element['neighborhood']
            Address_district = element['district']
            Address_city = element['city']
        html_message = render_to_string('payment/mail_template.html', {'user': request.user, 'basket_items':basket_items, 'subtotal':subtotal, 'total':total, 'discount':discount,'neighborhood':Address_neighborhood, 'district':Address_district, 'city':Address_city, 'name':Address_name, 'surname':Address_surname})
        plain_message = strip_tags(html_message)
        send_mail(subject,
            plain_message, EMAIL_HOST_USER, [recipient], html_message=html_message)
    return render(request, 'payment/modal.html', {'total': total})

payment/templates/payment/latest.html
<!DOCTYPE html>
<html>
<head>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <style>
        .vertical-menu {
            width: 200px;
            height: 150px;
            overflow-y: auto;
        }

        h3 {
            color: black;
        }

        h2 {
            color: black;
        }

        .btn-group button {
            background-color: crimson;
            border-radius: 5px;
            border: 2px solid white;
            padding: 10px 24px;
            color: white;
            cursor: pointer;
            width: 47%;
            display: block; /* Make the buttons appear below each other */
        }

        .btn-group button:not(:last-child) {
            border-bottom: none; /* Prevent double borders */
        }

        /* Add a background color on hover */
        .btn-group button:hover {
            background-color: crimson;
            cursor: pointer;
            cursor: hand;
            border-radius: 5px;
        }

        .button1 {
            background-color: crimson;
            border: none;
            color: white;
            border-radius: 5px;
            padding-left: 10px;
            padding: 8px 40px;
            text-align: center;
            text-decoration: none;
            display: inline-block;
            font-size: 16px;
            margin: 4px 2px;
            cursor: pointer;
        }

        * {
            box-sizing: border-box;
        }

        .row {
            display: -ms-flexbox;
            display: flex;
            -ms-flex-wrap: wrap;
            flex-wrap: wrap;
            margin: 0 -16px;
        }

        .col-25 {
            -ms-flex: 25%;
            flex: 25%;
        }

        .col-50 {
            -ms-flex: 50%;
            flex: 50%;
        }

        .col-75 {
            -ms-flex: 75%;
            flex: 75%;
        }

        .col-25,
        .col-50,
        .col-75 {
            padding: 0 16px;
        }


        input[type=text] {
            width: 100%;
            margin-bottom: 20px;
            padding: 12px;
            border: 1px solid #ccc;
            border-radius: 3px;
        }

        label {
            color: grey;
            margin-bottom: 10px;
            display: block;
        }

        .icon-container {
            margin-bottom: 20px;
            padding: 7px 0;
            font-size: 24px;
        }

        /* The Modal (background) */
        .modal {
            display: none; /* Hidden by default */
            position: fixed; /* Stay in place */
            z-index: 1; /* Sit on top */
            padding-top: 100px; /* Location of the box */
            left: 0;
            top: 0;
            width: 100%; /* Full width */
            height: 100%; /* Full height */
            overflow: auto; /* Enable scroll if needed */
            background-color: rgb(0, 0, 0); /* Fallback color */
            background-color: rgba(0, 0, 0, 0.4); /* Black w/ opacity */
        }

        /* Modal Content */
        .modal-content {
            background-color: #fefefe;
            margin: auto;
            padding: 20px;
            border: 10px solid #888;
            width: 35%;
            height: 70%;
            letter-spacing: 2px;
            text-align: center;
            line-height: 2;
            font-size: 17px;
            color: #1acd4c;
        }

        /* The Close Button */
        .close {
            color: #aaaaaa;
            float: right;
            font-size: 28px;
            font-weight: bold;
        }

        .close:hover,
        .close:focus {
            color: #000;
            text-decoration: none;
            cursor: pointer;
        }

        .btn {
            background-color: crimson;
            color: white;
            padding: 12px;
            margin: 10px 0;
            border: none;
            width: 100%;
            border-radius: 3px;
            cursor: pointer;
            font-size: 17px;
        }

        .btn:hover {
            background-color: crimson;
        }

        hr {
            border: 1px solid lightgrey;
        }

        span.price {
            float: right;
            color: grey;
        }

        @media (max-width: 800px) {
            .row {
                flex-direction: column-reverse;
            }

            .col-25 {
                margin-bottom: 20px;
            }
        }
    </style>
    {% load static %}

</head>
<div class="row">
    <div class="col-75">
        <div class="container" style="
        padding: 5px 20px 15px 20px;
        border: 1px solid lightgrey;
        border-radius: 3px;">

            <div class="row">
                <div class="col-50">
                <form action="{% url 'payment:confirm_payment' %}" method="POST">
                        {% csrf_token %} 
                    <h2>Billing Address</h2>
                    <label style="color:grey" for="fname"><i class="fa fa-user"></i> Full Name</label>
                    <input type="text" id="fname" name="firstname" placeholder="Name Surname">
                    <label style="color:grey" for="email"><i class="fa fa-envelope"></i> Email</label>
                    <input type="text" id="email" name="email" placeholder="something@example.com">
                    <div style="color:grey"><i class="fa fa-address-card-o"></i> Address</div>
                    <address id="def_add">
                        ITU International Office<br>
                        Ayazaga Campus<br>
                        Registrator's Office Building<br>
                        Maslak 34469 Sariyer/Istanbul<br>
                    </address>
                    <button class="button button1" id="button1">Change the Address</button>
                    <!-- <form id="addressForm" action="/ChangeAdress" method = "post" display="none"> -->
                    <textarea id="newAdd" rows="5" cols="60" name="description">defaultAddress</textarea>
                    <!-- defaultAdressi her seferinde güncelle  -->
                    <button class="button button1" id="button2" display="none">Ok</button>
                    <!-- </form> -->

                    <br>
                    <br>
                    <i class="fa fa-money"></i> Payment Menu
                    <br><br>
                    <div class="btn-group">
                        <button>Credit Card</button>
                        <button>Pay on Delivery</button>
                    </div>

                </div>

                <div class="col-50">
                    <h3>Payment</h3>
                    <label for="fname">Accepted Cards</label>
                    <div class="icon-container">
                        <i class="fa fa-cc-visa" style="color:crimson;"></i>
                        <i class="fa fa-cc-amex" style="color:crimson;"></i>
                        <i class="fa fa-cc-mastercard" style="color:crimson;"></i>
                        <i class="fa fa-cc-discover" style="color:crimson;"></i>
                    </div>
                    <label for="cname">Name on Card</label>
                    <input type="text" id="cname" name="cardname" placeholder="Name Surname">
                    <label for="ccnum">Credit card number</label>
                    <input type="text" id="ccnum" name="cardnumber" placeholder="XXXX-XXXX-XXXX-XXXX">
                    <div class="col-30">
                        <label for="expmonth">Expiry Month</label>
                        <select name="month" id="expmonth" placeholder="Month">
                            <option value="1">01</option>
                            <option value="2">02</option>
                            <option value="3">03</option>
                            <option value="4">04</option>
                            <option value="5">05</option>
                            <option value="6">06</option>
                            <option value="7">07</option>
                            <option value="8">08</option>
                            <option value="9">09</option>
                            <option value="10">10</option>
                            <option value="11">11</option>
                            <option value="12">12</option>
                        </select>
                    </div>
                    <br/>
                    <div class="col-30">
                        <label for="selectYear">Expiry Year</label>
                        <select id="selectYear" name="month" placeholder="Year">
                            <option value="1">01</option>

                        </select>
                    </div>
                    <br/>
                    <div class="col-30">
                        <label for="cvv">CVV</label>
                        <input type="number" id="cvv" min="0" pattern=".{3,4}" name="cvv" placeholder="XXX"
                               autocomplete="off" tabindex="8">
                    </div>
                </div>

            </div>

            <br>
            <label>
                <input type="checkbox" checked="checked" name="sameadr"> Acceptance of general terms and conditions
            </label>
        </div>
    </div>
    <div class="col-25">
        <div class="container" style="color:grey;
        padding: 5px 20px 15px 20px;
        border: 1px solid lightgrey;
        border-radius: 3px;">
      
            <h2>Cart <span class="price" style="color:grey;"><i class="fa fa-shopping-cart"></i></span></h2>
            <p>Subtotal <span class="price">${{ subtotal }}</span></p>
            <p>Discount<span class="price">${{ discount }}</span></p>
            <p>Shipping<span class="price">$0.0</span></p>
            <hr>
            <p>Total <span class="price" style="color:black"><b>${{ total }}</b></span></p>
            <button type="submit" id="pay" class="button button1">PAY</button>

        </form>
        </div>
    </div>
    <!-- The Modal -->
    <div id="myModal" class="modal">

        <!-- Modal content -->
        <div class="modal-content">
            <span class="close">&times;</span>
            <br>
            <p> THANK YOU!</p>
            <img src="{% static "payment\icon.png" %}" height="120" width="120">
            <br>
            <p style="font-size:22px;color: black;">${{ total }}</p>
            <p style="color: black">YOUR ORDER HAS BEEN CONFIRMED</p>
            <p style="font-size:15px;">A RECEIPT WAS SENT TO YOUR EMAIL </p>
        </div>

    </div>

</div>
<!--<script src="jquery-3.5.1.js"></script>-->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script>
    // Get the modal
    var modal = document.getElementById("myModal");

    // Get the button that opens the modal
    var btn = document.getElementById("pay");

    // Get the <span> element that closes the modal
    var span = document.getElementsByClassName("close")[0];

    // When the user clicks the button, open the modal
    // btn.onclick = function () {
    //     modal.style.display = "block";
    // }

    // When the user clicks on <span> (x), close the modal
    span.onclick = function () {
        modal.style.display = "none";
    }

    // When the user clicks anywhere outside of the modal, close it
    window.onclick = function (event) {
        if (event.target == modal) {
            modal.style.display = "none";
        }
    }
</script>
<script>
    $(document).ready(function () {
        var $def_add = $('#def_add'); // document.getElementById("def_add")
        var $addressForm = $('#addressForm');
        var $newAdd = $('#newAdd');
        var $button2 = $('#button2');
        var $button1 = $('#button1');
        var $selectYear = $('#selectYear');

        $newAdd.hide()
        $button2.hide()

        $button1.click(function () {
            $def_add.hide(); // document.getElementById("def_add").style.display= "none";
            $addressForm.show();
            $newAdd.show();
            $button2.show();
            $button1.hide();

        })

        $button2.click(function () {
            var $new_val = $newAdd.val();
            $def_add.show();
            $def_add.text($new_val); // document.getElementById("def_add").innerHTML = document.getElementById("newAdd").value
            $newAdd.hide();
            $button1.show();
            $button2.hide();
            $addressForm.hide();

        })

        let options = ``;
        ``
        let start = 2020;
        let end = 2055;
        for (let year = start; year <= end; year++) {
            options += `<option>${year}</option>`
        }
        $selectYear.html(options);


    });

</script>
</body>
</html>

payment/templates/payment/modal.html
<!DOCTYPE html>
<html>
<head>
{% load static %}
<style>
    .modal {
            /* display: none; Hidden by default */
            position: fixed; /* Stay in place */
            z-index: 1; /* Sit on top */
            padding-top: 100px; /* Location of the box */
            left: 0;
            top: 0;
            width: 100%; /* Full width */
            height: 100%; /* Full height */
            overflow: auto; /* Enable scroll if needed */
            background-color: rgb(0, 0, 0); /* Fallback color */
            background-color: rgba(0, 0, 0, 0.4); /* Black w/ opacity */
        }

        /* Modal Content */
        .modal-content {
            background-color: #fefefe;
            margin: auto;
            padding: 20px;
            border: 10px solid #888;
            width: 35%;
            height: 70%;
            letter-spacing: 2px;
            text-align: center;
            line-height: 2;
            font-size: 17px;
            color: #1acd4c;
        }
</style>
</head>
<body>
 <!-- The Modal -->
<div id="myModal" class="modal">

    <!-- Modal content -->
    <div class="modal-content">
        <span class="close">&times;</span>
        <br>
        <p> THANK YOU!</p>
        <img src="{% static "payment/icon.png" %}" height="120" width="120">
        <br>
        <p style="font-size:22px;color: black;">{{ total|floatformat:2 }} ₺</p>
        <p style="color: black">YOUR ORDER HAS BEEN CONFIRMED</p>
        <p style="font-size:15px;">A RECEIPT WAS SENT TO YOUR EMAIL </p>
    </div>

</div>
</body>